# -*- coding: utf-8 -*-
"""problem2_r.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hUQOnQtOYXWcxCFajMZmTQ3mouD5RaQU

1 and 2. First I create and display the data from the csv file as a dataframe. In order to import the data I had to upload the nutrition_subset.csv file to the session storage before I could read it and create a dataframe
"""

#Set up dataframe and display it
data <- read.csv("nutrition_subset.csv")
nutritionDF <- data
head(nutritionDF, 100)

"""3.It is not valid to compare foods of different sizes because foods of larger sizes would naturally be more likely to have more saturated fat, while they are foods that might have less overall saturated fat, but more saturated fat per gram. This means that using saturated fat per gram is better because it takes into account the differences in size of the different foods"""

#Displays the highest 5 values for the sorted df based on saturated fat
head(nutritionDF[order(nutritionDF$saturated_fat, decreasing=TRUE), 1:4], 5)

"""4. After sorting the data based on saturated fat per gram, I found that 1 tablespoon of salted butter has the most saturated fat per gram with about 0.507"""

#Loops through all rows and creates the coloumn saturated fat per gram
for (row in nrow(nutritionDF)) {
  nutritionDF$saturated_fat_per_gram <- nutritionDF$saturated_fat / nutritionDF$weight_in_grams
}
#Sorts the df by saturated fat per gram and displays the highest 5 values
head(nutritionDF[order(nutritionDF$saturated_fat_per_gram, decreasing=TRUE), 1:5], 5)

"""5.After standardizing the data using z score and looking for outliers, I found there to be 15 high end outliers and 0 low end outliers. Based on the density plot, most of the values are near the mean, which is a little bit more than 0 (about 0.02) based on the plot"""

#Creates column for scaled saturated fat per gram and populates the values with eachrespective z score
nutritionDF$scaled_saturated_fat_per_gram <- scale(x = nutritionDF$saturated_fat_per_gram)
#Displays the rows that have a scaled saturated fat per gram greater than 3
subset(nutritionDF, scaled_saturated_fat_per_gram > 3)

#Displays the number of rows that have a scaled saturated fat per gram less than -3
nrow(subset(nutritionDF, scaled_saturated_fat_per_gram < -3))

#Builds and displays density plot for unscaled saturated fat per gram
par(mfrow=c(1, 2))
d1 <- density(nutritionDF$saturated_fat_per_gram)
plot(d1, main="Unscaled Saturated Fat per Gram")
polygon(d1, col="orange", border="blue")
#Builds and displays density plot for scaled saturated fat per gram
d2 <- density(nutritionDF$scaled_saturated_fat_per_gram)
plot(d2, main="Scaled Saturated Fat per Gram")
polygon(d2, col="orange", border="blue")

"""6. There appears to be no missing values in this data"""

install.packages("Hmisc")
library(Hmisc)

#Checks for missing values
cat(sum(is.na(nutritionDF)))

"""7. I standardize the data for the rest of the numerical values and check for outliers. In addition to the 15 outliers I found before for the saturated fat per gram, I found weight in grams to have 22 outliers, saturated fat to have 20 outliers, and cholesterol to have 17 outliers."""

#Creates column for scaled weight in grams and populates the values with each respective z score
nutritionDF$scaled_weight_in_grams <- scale(x = nutritionDF$weight_in_grams)
#Displays the amount of rows where scaled weight in grams is greater than 3 or less than -3.
nrow(subset(nutritionDF, scaled_weight_in_grams > 3)) + nrow(subset(nutritionDF, scaled_weight_in_grams < -3))

#Creates column for scaled saturated fat and populates the values with each respective z score
nutritionDF$scaled_saturated_fat <- scale(x = nutritionDF$saturated_fat)
#Displays the amount of rows where scaled saturated fat is greater than 3 or less than -3.
nrow(subset(nutritionDF, scaled_saturated_fat > 3)) + nrow(subset(nutritionDF, scaled_saturated_fat < -3))

#Creates column for scaled cholesterol and populates the values with each respective z score
nutritionDF$scaled_cholesterol <- scale(x = nutritionDF$cholesterol)
#Displays the amount of rows where scaled cholesterol is greater than 3 or less than -3.
nrow(subset(nutritionDF, scaled_cholesterol > 3)) + nrow(subset(nutritionDF, scaled_cholesterol < -3))

#Displays df
head(subset(nutritionDF, scaled_saturated_fat > 3), 100)

"""8. Summary: After importing the data and creating a dataframe with it, I sorted the data by the saturated fat and found the 5 highest values. The hightest out of those was 1 cheesecake with a saturated fat value of 119.9. However this isn't a valid way to find which food has the most saturated fat because it doesn't take into account the size of the food. To do that, We can use saturated fat per gram, which gives a more accurate picture on what foods have the most saturated fat. After finding the saturated fat per gram for each food and sorting the data and diplaying the 5 highest values based on saturated fat per gram, I found the food with the highest value to be 1 tablespoon of salted butter with a saturated fat per gram of 0.507. After this I standardized the saturated fat per gram and checked for outliers. I found 15 high end outliers and 0 low end outliers. After this I created a denstity plot for the unscaled and scaled saturated fat per gram and found that most of the values were close to the mean and that the mean is slightly over 0 (about 0.02). At this point I also checked for missing values and didn't find any. Finally I standardized the other 3 numeric variables and checked if they had any outliers. Weight per gram had 22, saturated fat had 20, and cholesterol had 17."""